server.default_listen_address=0.0.0.0

server.memory.heap.initial_size=512m
server.memory.heap.max_size=2G
server.memory.pagecache.size=512m

server.directories.logs=/logs
server.directories.data=/data

dbms.security.procedures.unrestricted=apoc.*

server.bolt.enabled=true
server.http.enabled=true
